apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-demo-config
  namespace: contoso-air
  labels:
    app.kubernetes.io/name: contoso-air-demo
    kubernetes.azure.com/generator: devhub
data: