apiVersion: v1
kind: Service
metadata:
  name: contoso-air-demo
  namespace: contoso-air
  labels:
    app.kubernetes.io/name: contoso-air-demo
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contoso-air-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000